starsocial/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path(r'login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name = 'login'),
    path(r'logout/',auth_views.LogoutView.as_view(),name = 'logout'),
    path(r'signup/',views.SignUp.as_view(),name='signup'),
    path(r'token/',views.Token_send.as_view(),name='token_send'),
    path(r'success/',views.Success.as_view(),name='success'),
    path(r'verify/<slug>/',views.Verify.as_view(),name='verify'),
    path(r'error/',views.Error.as_view(),name='error'),
    # path(r'register/',views.register_attempt,name='register_attempt')


]

starsocial/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns  = [
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create'),
    path('by/<username>/',views.UserPosts.as_view(),name='for_user'),
    path('by/<username>/<int:pk>/',views.PostDetail.as_view(),name='single'),
    path('delete/<int:pk>/',views.DeletePost.as_view(),name='delete')
]

starsocial/starsocial/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('posts/',include('posts.urls',namespace='posts')),
    path('groups/',include('groups.urls',namespace='groups')),
]

starsocial/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Star Social</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Alternative to Bootstrap 3 Glyphicons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'starsocial/css/master.css'%}">


  </head>
  <body>

    <nav class="navbar navbar-expand-lg" role="navigation" id="navbar">
      <div class="container">
        <a class="navbar-brand mynav"href="{% url 'home'%}">Star Social</a>

        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li> <a href="{% url 'posts:create' %}">Post</a> </li>
            <li><a href="{% url 'groups:all'%}">Groups</a></li>
            <li><a href="{% url 'groups:create'%}">Create Group</a></li>
            <li><a href="{% url 'accounts:logout'%}">Log Out</a></li>
          {% else %}
            <li><a href="{% url 'groups:all'%}">Groups</a> </li>
            <li><a href="{% url 'accounts:login'%}">Log In</a> </li>
            <li><a href="{% url 'accounts:signup'%}">Sign Up</a> </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container mycontent">

      {% block content %}




      {% endblock %}

    </div>

    <canvas id="canvas"></canvas>
  </body>

  <script type="text/javascript" src="{% static 'starsocial/js/master.js' %}">

  </script>


</html>

starsocial/templates/index.html
{% extends "base.html" %}

{% block content %}

    <h1>Welcome to Star Social!</h1>

{% endblock %}

starsocial/templates/test.html
{% extends "base.html" %}
{% block content %}

<h1>You are now Logged in!</h1>

{% endblock %}

starsocial/templates/thanks.html
{% extends "base.html" %}
{% block content %}

<h1>Thanks for visiting, come back soon!</h1>

{% endblock %}